### ISSUE TITLE
conda and pip installation files

### ISSUE THREAD

**Issue by cmoestl** [University-of-Reading-Space-Science/HUXt#2]
Hi, very nice work! it would be best if you could add the environment.yml and requirements.txt files, e.g. see "Installation" in https://github.com/cmoestl/heliocats
(with the files in this repository defining our "standard" enviroment which we call "helio")
so one can immediately make an environment to run the code without the need to figure out which packages or different versions are needed.

edit: so now I run the code and after installing my "helio" environment + pip install h5py + pip install moviepy importing is fine; it then stops at model.solve(cme_list, save=True, tag='1d_conecme_test') with a numpy error as probably we use different numpy versions,

ciao chris

**Comment by LukeBarnard** [comment]
Hi Chris,

Thanks for this. You're right this would be better. It's been on the to-do list, but never quite made it to the top. I have some time to look at it this week though.

Can you let me know what version of numpy you are using and what the error message was?

Thanks for your help,

Cheers,

**Comment by cmoestl** [comment]
I tried it with numpy 1.18.1, and also numpy 1.16.2 (in my helio environment) but I always get this error, see screenshot 
![Bildschirmfoto 2020-03-23 um 09 07 50](https://user-images.githubusercontent.com/14162616/77300349-2fe87080-6cee-11ea-8e87-ec57bcaf1726.jpg)

This is a basic environment.yml file that works for importing (no pip required):

name: huxt
dependencies:
  - python==3.7.6
  - numpy==1.18.1
  - matplotlib==3.1.2
  - ipython==7.11.1
  - pip==19.3.1
  - numba==0.45.1
  - scipy==1.3.1
  - sunpy==1.1.0
  - scikit-learn==0.20.3
  - scikit-image==0.15.0
  - pandas==0.25.3
  - seaborn==0.9.0
  - astropy==4.0
  - moviepy==1.0.1 
  - h5py==2.10.0

**Comment by LukeBarnard** [comment]
Thanks Chris - I'll have a look at this today.

**Comment by STBadman** [comment]
Agreed, very nice work! I was initially getting the same error as above running through the demo notebook. The issue was some instances of `np.interp` in which the value to be interpolated was an np.array containing astropy.unit.Quantity objects, e.g. line 854 :

`v_boundary_update = np.interp(self.lon.value, lon_tstep.value, v_boundary_cone)`

`np.interp` seemed to strip the units away, so `v_boundary_cone` entered with units km/s but `v_boundary_update` became just a normal np.array of floats, and then your save method runs into problems because it expects all the arrays it encounters to have units.

I updated numpy and astropy (now versions numpy.__version__ : 1.18.1, astropy.__version__ = 4.0) and now it seems to work as packaged. I agree an environment file would be handy for consistency.

**Comment by LukeBarnard** [comment]
Hey,

Thanks both for your feedback here, it's apprecated. I've added the requirements.txt and environment.yml files and updated the README. Hopefully this makes things a bit clearer now. I'll admit I don't tend to use virtual environments, so I was a bit slow to catch on. 

On my machine, creating the conda environment and running the notebook examples works OK. Please let me know if you have any further problems!

Cheers,

**Comment by cmoestl** [comment]
the example notebook works like a charm on MacOSX with this environment, only needed to change the paths to / in config.dat, thanks much!

**Comment by LukeBarnard** [comment]
Great. Thanks for checking. I'll leave this open for a while to see if any similar problems occur.
